### ISSUE TITLE
Cannot build without charting_library

### ISSUE THREAD

**Issue by goozeberry** [econia-labs/econia-frontend#211]
Honk I get these errors
    
```
Module not found: Can't resolve '../../../public/static/charting_library' in '/vercel/path0/src/frontend/src/components/trade'
--
15:37:43.608 |  
15:37:43.608 | Import trace for requested module:
15:37:43.608 | ./src/components/trade/TVChartContainer.tsx
15:37:43.608 |  
15:37:43.608 | ./src/pages/market/[market_id].tsx
15:37:43.608 | Module not found: Can't resolve '../../../public/static/charting_library' in '/vercel/path0/src/frontend/src/pages/market'
15:37:43.608 |  
15:37:43.609 | ./src/pages/market/[market_id].tsx
15:37:43.609 | Module not found: Can't resolve '../../../public/static/charting_library' in '/vercel/path0/src/frontend/src/pages/market'
```

**Comment by alnoki** [comment]
@goozeberry is this a build log from Vercel?

Note that if you are trying to build on Vercel, you'll need to set the environment variables: https://github.com/econia-labs/econia-frontend?tab=readme-ov-file#1---environment-preparation

As described on the README, you do not actually need the charting library to build the project, but you'll need to make sure you set `TRY_CLONING_TRADINGVIEW` to something other than 1

**Comment by alnoki** [comment]
@goozeberry as of #217 you can now fallback on an open source version
