### ISSUE TITLE
Balance undefined for mainnet

### ISSUE THREAD

**Issue by goozeberry** [econia-labs/econia-frontend#212]
Is undefined on this line: https://github.com/goozeberry/econia-frontend/commit/5909f28a5a82fb7559739907c687dc4cf58c50bb#diff-01d3e6595ae2cc66e21de50a65cd09bd8b198f8ea0f1e8fe944ddff1586391e2R41.

Maybe market data undefined  on mainnet without charting view?

**Comment by alnoki** [comment]
@goozeberry it looks like you have deployed the frontend on mainnet. Have you connected a wallet that is also on mainnet? You may experience issues if you do not set your wallet to mainnet as well

**Comment by xbtmatt** [comment]
Hmm, I can't seem to reproduce the issue. If you put your address in this call, do you get valid JSON data back? Even if the specified coin isn't registered, it should still return `[]`, see this for example:

https://aptos-mainnet-econia.nodeinfra.com/rpc/user_balance?user_address=0xb89f7389d4005673ed059804dad64d010bf64c1dc1bf4ce2433ba818c3f9114d&market=7&custodian=0

In which case, the `balance` value would be:

```json
{
    "base_total": null,
    "base_available": null,
    "base_ceiling": null,
    "quote_total": null,
    "quote_available": null,
    "quote_ceiling": null
}
```

Do you mind trying to explain more how to reproduce the issue? 😄

**Comment by alnoki** [comment]
Closing due to no response
