### ISSUE TITLE
Market data is empty on testnet

### ISSUE THREAD

**Issue by 0xaptosj** [econia-labs/econia-frontend#214]
Hi, I'm trying to run the frontend on testnet, but `https://aptos-testnet-econia.nodeinfra.com/markets` returns empty array, causing market page unable to load.

**Comment by alnoki** [comment]
@0xaptosj https://aptos-testnet-econia.nodeinfra.com/markets has data in it now

Note that Aptos Labs put recently put out some experimental features on testnet that broke indexer processors, including the one in the Econia Data Service Stack (which Nodeinfra is running)

They've been redeploying with a patched version and we are collaborating to ensure data integrity

**Comment by alnoki** [comment]
Noting that I was just able to run the frontend using the testnet config from the repo

**Comment by 0xaptosj** [comment]
Nice, confirmed it's also working for me now!
