### ISSUE TITLE
Is it possible to replace `charting_library` with `lightweight-charts`?

### ISSUE THREAD

**Issue by 0xaptosj** [econia-labs/econia-frontend#215]
Currently frontend depends on a private repo `charting_library` of trading view which I guess need to be paid to gain access. Trading view has an [open source chart](https://github.com/tradingview/lightweight-charts), do you guys have an estimation on the feasibility of using it to replace `charting_library`?

**Comment by xbtmatt** [comment]
I'll look into it and see! I think it's possible but I'll need to look into it to see how limited lightweight-charts is compared to what the current frontend is using

**Comment by alnoki** [comment]
Closed in #217
